spring:
  application:
    name: springai

  datasource:
    hikari:
      url: jdbc:h2:tcp://localhost/C:\workspace\11_SpringBoot\springai/tdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    h2:
      console:
        enabled: true
        path: /h2-console
  ai:
    openai:
      api-key:

server:
  port: 8001