CREATE TABLE FORM(
    FORM_NO NUMBER PRIMARY KEY,
    FORM_TITLE VARCHAR2(100) NOT NULL,
    FORM_WRITER VARCHAR2(30) NOT NULL,
    FORM_RESPONSE_URL VARCHAR2(100),
    FORM_DASHBOARD_URL VARCHAR2(100),
    CREATE_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    FOREIGN KEY (FORM_WRITER) REFERENCES MEMBER ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_FNO
NOCACHE;

